### ISSUE TITLE
progress for the workflow

### ISSUE THREAD

**Issue by keewis** [pangeo-fish/pangeo-fish#3]
Tasks to complete for the workflow:
- [x] step notebooks
  - [x] difference computation
  - [x] regridding to healpix (#2)
  - [x] emission probability computation and preparation of other conditions (#4)
  - [x] transformation of acoustic measurements to emission probabilities (#7)
  - [x] optimization of the model parameters (#9)
  - [x] track decoding
- [ ] workflow execution
  - [x] batch script for jobqueue submission (#6)
  - [ ] workflow management configuration (airflow?)
  - [ ] cluster management using `dask-ctl` (prerequisite: `dask-ctl` support for `LocalCluster` / `dask-jobqueue`)
