### ISSUE TITLE
Preparation of JOSS submission Checklist

### ISSUE THREAD

**Issue by tinaok** [pangeo-fish/pangeo-fish#35]
- [x] Separate Automatic Submitting Part
  - [x] Copy automatic submitting parts to a separate repository. (pangeo-fish-runner)
  - [x] verify the new repository work. 
- [x] Clean Repository Structure
  - [x] take out automatic submitting part
  - [x] Update README with instructions. 
     
- [x] Refactor Notebook Examples
  - [x] Transform parts of notebook examples into functions within the codebase.
  - [x] Create a comprehensive notebook executing all functions with markdown explanations.
  - [x] Remove Old Notebook Examples
    - Clean up outdated or unnecessary notebook examples.
- [x] #126
- [x] Write Markdown and BibTeX for JOSS
- [x] Clean & Improve codes
  - [x] Add documentation for programmatically interacting with the code.
- [x] metadata for the software
